trigger:
  none
  

name: Azure Pipelines
variables:
  python.version: '3.7.6'
stages:
- stage: Provisioning
  displayName: Provisioning
  jobs: 
  - job: ProvisioningAppService
    displayName: Provisioning AppService
    steps:
    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: 'default'
        sshKeySecureFile: 'id_rsa'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          ls /home/vsts/work/_temp/